[package]
name = "cats"
version = "0.1.0"
authors = ["Aleksei Korzun <akorzun@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
sdl2 = "0.32.2"